FROM golang:1.9

WORKDIR /go/src/github.com/shubhanshus/myevents/
COPY . .
WORKDIR src/eventservice
RUN CGO_ENABLED=0 GOOS=linux go build -a -installsuffix cgo -o eventservice

FROM scratch

COPY --from=0 github.com/shubhanshus/myevents/src/eventservice/eventservice /eventservice
ENV LISTEN_URL=0.0.0.0:8181
EXPOSE 8181
CMD ["/eventservice"]
